### ISSUE TITLE
fasm does not work with the xilinx-upstream-k7 branch of nextpnr-xilinx

### ISSUE THREAD

**Issue by hansfbaier** [kintex-chatter/xc7k325t-blinky-nextpnr#2]
When I build the k7 branch (and after rebuilding the chipdb),
then fasm2frames gives me this error:
```
+ fasm2frames --part xc7k325tffg676-1 --db-root /usr/local/share/nextpnr/prjxray-db/kintex7 blinky.fasm
Traceback (most recent call last):
  File "/usr/local/bin/fasm2frames", line 11, in <module>
    load_entry_point('prjxray', 'console_scripts', 'fasm2frames')()
  File "/devel/HDL/prjxray/utils/fasm2frames.py", line 303, in main
    run(
  File "/devel/HDL/prjxray/utils/fasm2frames.py", line 188, in run
    assembler.parse_fasm_filename(filename_in, extra_features=extra_features)
  File "/devel/HDL/prjxray/prjxray/fasm_assembler.py", line 190, in parse_fasm_filename
    raise FasmLookupError('\n'.join(missing_features))
prjxray.fasm_assembler.FasmLookupError: Segment DB LIOB33, key LIOB33.IOB_Y0.LVCMOS12_LVCMOS15_LVCMOS18_LVCMOS25_LVCMOS33_LVTTL_SSTL135.IN_ONLY not found from line 'LIOB33_X0Y125.IOB_Y0.LVCMOS12_LVCMOS15_LVCMOS18_LVCMOS25_LVCMOS33_LVTTL_SSTL135.IN_ONLY'
Segment DB LIOB33, key LIOB33.IOB_Y0.LVCMOS12_LVCMOS15_LVCMOS18_LVCMOS25_LVCMOS33_LVTTL_SSTL135.SLEW.SLOW not found from line 'LIOB33_X0Y113.IOB_Y0.LVCMOS12_LVCMOS15_LVCMOS18_LVCMOS25_LVCMOS33_LVTTL_SSTL135.SLEW.SLOW'
``

**Comment by jrrk2** [comment]
Issue previously addressed, closing
